# Generated by Django 4.2 on 2026-03-11 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=100)),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("ac", "AC"),
                            ("non_ac", "Non AC"),
                            ("sleeper", "Sleeper"),
                            ("seater", "Seater"),
                            ("ac_sleeper", "AC Sleeper"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bus_number", models.CharField(max_length=20, unique=True)),
                ("total_seats", models.IntegerField()),
                (
                    "seat_layout",
                    models.CharField(
                        choices=[
                            ("2x2", "2 x 2 (4 seats per row)"),
                            ("2x1", "2 x 1 (3 seats per row)"),
                            ("1x2", "1 x 2 (3 seats per row)"),
                            ("sleeper_2x1", "Sleeper 2 x 1"),
                            ("sleeper_1x1", "Sleeper 1 x 1"),
                        ],
                        default="2x2",
                        max_length=20,
                    ),
                ),
                (
                    "amenities",
                    models.TextField(
                        blank=True, help_text="AC, WiFi, Charging point, etc."
                    ),
                ),
                (
                    "bus_image",
                    models.ImageField(blank=True, null=True, upload_to="bus_images/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "bus_owner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g., 5 hours 30 mins", max_length=50
                    ),
                ),
                ("fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_seats", models.IntegerField()),
                (
                    "operating_days",
                    models.CharField(
                        default="All Days",
                        help_text="Mon,Tue,Wed,Thu,Fri,Sat,Sun",
                        max_length=100,
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="bus_owners.bus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnerBankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_holder_name", models.CharField(max_length=100)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
                ("ifsc_code", models.CharField(max_length=20)),
                (
                    "upi_id",
                    models.CharField(
                        help_text="Enter your UPI ID (e.g., name@okhdfcbank)",
                        max_length=50,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "phonepe_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "googlepay_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "paytm_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "bus_owner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_name", models.CharField(max_length=100)),
                (
                    "stop_order",
                    models.IntegerField(help_text="Order of stop in the journey"),
                ),
                ("arrival_time", models.TimeField()),
                ("departure_time", models.TimeField()),
                (
                    "stop_duration",
                    models.IntegerField(default=5, help_text="Duration in minutes"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="bus_owners.route",
                    ),
                ),
            ],
            options={
                "ordering": ["stop_order"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("window", "Window"),
                            ("aisle", "Aisle"),
                            ("middle", "Middle"),
                            ("sleeper_lower", "Sleeper Lower"),
                            ("sleeper_upper", "Sleeper Upper"),
                        ],
                        default="window",
                        max_length=20,
                    ),
                ),
                ("seat_row", models.IntegerField()),
                ("seat_column", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="bus_owners.bus",
                    ),
                ),
            ],
            options={
                "ordering": ["seat_row", "seat_column"],
                "unique_together": {("bus", "seat_number")},
            },
        ),
    ]
